name: Build Weather API Container
on: [push]
env:
  DOCKER_REGISTRY: ${{ secrets.DOCKER_USERNAME }}.azurecr.io
  IMAGE_NAME: hackfest/weather-api
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Code
      uses: actions/checkout@master

    - name: Docker Login
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.DOCKER_REGISTRY }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Docker Build and Push
      run: |
        docker build . -t $DOCKER_REGISTRY/$IMAGE_NAME:${{ github.sha }} -t $DOCKER_REGISTRY/$IMAGE_NAME:1.0 -t $DOCKER_REGISTRY/$IMAGE_NAME:latest
        docker push $DOCKER_REGISTRY/$IMAGE_NAME:${{ github.sha }}
        docker push $DOCKER_REGISTRY/$IMAGE_NAME:1.0
        docker push $DOCKER_REGISTRY/$IMAGE_NAME:latest